### PR TITLE
feat: Addition of Extra User Fields

### PR DESCRIPTION
**Pull request by AyakorK**
#### :tophat: Description
*Please describe your pull request.*

This PR adds the module Extra User Fields to the CDC and modifies a bit the create_registration command to ensure the compatibility between the custo previously made and this module

#### :pushpin: Related Issues

- [Notion card](https://www.notion.so/opensourcepolitics/Cour-des-comptes-Ajout-module-extra-sign-up-fields-d5915b355a0b40a4b9692988047b8c02?pvs=4)

#### Testing
*Describe the best way to test or validate your PR.*

### 💾  Back Office Setup
- Before launching your app make sure you precompiled Deface to ensure the fields appears in the registration form by running `bundle exec rake deface:precompile`
-  Access to Back Office
-  Click on Settings
- Access EUF settings
- Enable any field you want

### 🖼️ Front Office Test
- As a disconnected user, click on the `Register` Button
- Make sure that your previously added extra user fields are appearing correctly
- Fill in your form and submit it
- Make sure you can register easily without any crash
- Check your mails if you receive correctly mails (Make sure to activate Underage Field if you want to have the statutory representative email at the end)

#### Tasks
- [x] Add specs
- [x] Import the create_registration_command from EUF to fix the issue of Email Representative (not working we need to figure out why)
- [x] Addition of few migrations related to EUF

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

### CODE REVIEW

**Review by luciegrau — APPROVED** [review]

**Review by BarbaraOliveira13 — COMMENTED** [review]
I ran it, and I have the extra user fileds that repeat twice : 
Capture d’écran 2024-07-22 à 11 24 17
Capture d’écran 2024-07-22 à 11 44 39

Other than this, it works great when I register 👍 

I don't know if it's necessary to spend time on it...just a suggestion: add an 's' to 'Plus d'informations' when there are more than 2 fields ? 🤷‍♀️

**Review by BarbaraOliveira13 — APPROVED** [review]

**Comment by AyakorK** [comment]
> I ran it, and I have the extra user fileds that repeat twice (@luciegrau I am the only one ? :s) : Capture d’écran 2024-07-22 à 11 24 17 Capture d’écran 2024-07-22 à 11 44 39
> 
> Other than this, it works great when I register 👍
> 
> I don't know if it's necessary to spend time on it...just a suggestion: add an 's' to 'Plus d'informations' when there are more than 2 fields ? 🤷‍♀️

Heyy for the first issue this might be an issue related to Deface and the precompilation of it. Check if you have a local folder named "compiled_views" and try to delete it and to run it again if you want to try ! 

Otherwise for the other issue yeah this might be something to fix but that is actually on the module itself ! Let's wait for Lucie's answer to see if this is something important to fix

**Comment by luciegrau** [comment]
Hi @BarbaraOliveira13 and @AyakorK! 
I didn't get the same error as Barbara when I launched the PR locally, I think it was linked to Deface. 
As for Barbara's suggestion for improvement, I agree with her. This has already been pointed out by some clients and we could implement this change directly in the extra user fields module. 
However, there's no need to wait for this improvement to bump the module to decidim-cdc since they're only going to activate the phone number field.

**Comment by BarbaraOliveira13** [comment]
> > I ran it, and I have the extra user fileds that repeat twice (@luciegrau I am the only one ? :s) : Capture d’écran 2024-07-22 à 11 24 17 Capture d’écran 2024-07-22 à 11 44 39
> > Other than this, it works great when I register 👍
> > I don't know if it's necessary to spend time on it...just a suggestion: add an 's' to 'Plus d'informations' when there are more than 2 fields ? 🤷‍♀️
> 
> Heyy for the first issue this might be an issue related to Deface and the precompilation of it. Check if you have a local folder named "compiled_views" and try to delete it and to run it again if you want to try !
> 
> Otherwise for the other issue yeah this might be something to fix but that is actually on the module itself ! Let's wait for Lucie's answer to see if this is something important to fix

Ok I will try again asap to understand ;) but it's just me, obviously. Great job! And thanks for the details :)

**Review by Quentinchampenois — APPROVED** [review]

**Pull request merged**
